
const motivos = {
    1: "porque você é a mulher mais encantadora desse mundo!",
    2: "porque seu cheiro é perfeito!",
    3: "porque você sabe fazer um carinho sem igual!",
    4: "porque você é minha melhor amiga!",
    5: "porque você tem o corpo perfeito!",
    6: "porque você ta sempre do meu lado!",
    7: "porque você me faz feliz!",
    8: "",
    9: "",
    10: "",
    11: "",
    12: "",
    13: "",
    14: "",
    15: "",
    16: "",
    17: "",
    18: "",
    19: "",
    20: "",
    21: "",
    22: "",
    23: "",
    24: "",
    25: "",
    26: "",
    27: "",
    28: "",
    29: "",
    30: "",
    31: "",
    32: "",
    33: "",
    34: "",
    35: "",
    36: "",
    37: "",
    38: "",
    39: "",
    40: "",
    41: "",
    42: ""
}

const momentos = {
    1: "quando eu limpo o olho com a ponta do seu nariz",
    2: "quando eu te encho de beijo",
    3: "quando a gente cozinha juntos",
    4: "quando a gente da banho no theo juntos",
    5: "quando a gente ri juntos",
    6: "quando a gente assiste filme coladinho",
    7: "quando a gente se aconchega na minha posição no sono",
    8: "",
    9: "",
    10: "",
    11: "",
    12: "",
    13: "",
    14: "",
    15: "",
    16: "",
    17: "",
    18: "",
    19: "",
    20: "",
    21: "",
    22: "",
    23: "",
    24: "",
    25: "",
    26: "",
    27: "",
    28: "",
    29: "",
    30: "",
    31: "",
    32: "",
    33: "",
    34: "",
    35: "",
    36: "",
    37: "",
    38: "",
    39: "",
    40: "",
    41: "",
    42: ""
}